backend:
  name: github
  repo: haithamitc-arch/noor-albedaya-website
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "صفحات الموقع"
    files:
      - file: "index.html"
        label: "الصفحة الرئيسية"
        name: "index"
        fields:
          - {label: "عنوان الموقع", name: "title", widget: "string"}
